-- Safe MemberHub schema migration.
-- This file intentionally avoids seed/demo inserts and destructive changes.

create extension if not exists pgcrypto;

alter table public.member_users add column if not exists avatar_url text;

alter table public.shops add column if not exists subscription_start_date date;
alter table public.shops add column if not exists subscription_end_date date;
alter table public.shops add column if not exists subscription_status text not null default 'active';
alter table public.shops add column if not exists subscription_plan text not null default 'standard';

alter table public.membership_cards add column if not exists secure_token text;
alter table public.membership_cards add column if not exists qr_payload text;
alter table public.membership_cards add column if not exists total_spend integer not null default 0;
create unique index if not exists cards_secure_token_unique_idx
  on public.membership_cards(secure_token)
  where secure_token is not null;

alter table public.transactions add column if not exists transaction_code text;
alter table public.transactions add column if not exists price integer not null default 0;
alter table public.transactions add column if not exists discount integer not null default 0;
alter table public.transactions add column if not exists tax integer not null default 0;
create unique index if not exists transactions_code_unique_idx
  on public.transactions(transaction_code)
  where transaction_code is not null;

create table if not exists public.membership_levels (
  id integer generated by default as identity primary key,
  shop_id integer not null references public.shops(id) on delete cascade,
  name text not null,
  color text,
  icon text,
  min_points integer not null default 0,
  min_spend integer not null default 0,
  earn_rate integer not null default 1,
  discount_percent integer not null default 0,
  benefits text,
  sort_order integer not null default 0,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (shop_id, name)
);

alter table public.membership_levels add column if not exists color text;
alter table public.membership_levels add column if not exists icon text;
alter table public.membership_levels add column if not exists earn_rate integer not null default 1;
alter table public.membership_levels add column if not exists sort_order integer not null default 0;

create table if not exists public.point_histories (
  id integer generated by default as identity primary key,
  shop_id integer not null references public.shops(id) on delete cascade,
  customer_id integer not null references public.customers(id) on delete cascade,
  card_id integer references public.membership_cards(id) on delete set null,
  transaction_id integer references public.transactions(id) on delete set null,
  points_before integer not null default 0,
  points_delta integer not null default 0,
  points_after integer not null default 0,
  reason text,
  actor_id integer references public.member_users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.subscription_renewals (
  id integer generated by default as identity primary key,
  shop_id integer not null references public.shops(id) on delete cascade,
  old_end_date date,
  new_end_date date not null,
  months integer,
  actor_id integer references public.member_users(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists shops_subscription_status_idx
  on public.shops(subscription_status, subscription_end_date);
create index if not exists membership_levels_shop_idx
  on public.membership_levels(shop_id);
create index if not exists point_histories_shop_customer_idx
  on public.point_histories(shop_id, customer_id, created_at desc);
create index if not exists subscription_renewals_shop_created_idx
  on public.subscription_renewals(shop_id, created_at desc);

alter table public.membership_levels enable row level security;
alter table public.point_histories enable row level security;
alter table public.subscription_renewals enable row level security;

update public.membership_cards
set secure_token = encode(gen_random_bytes(24), 'hex')
where secure_token is null;

update public.membership_cards
set qr_payload = '/member/' || secure_token
where secure_token is not null
  and (qr_payload is null or qr_payload like 'memberhub://card/%');
